name: servlet-mysql

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
      MYSQL_ROOT_PASSWORD: test_root_password
      TZ: Asia/Tokyo
    volumes:
      - servlet-mysql-store:/var/lib/mysql
      - ./config/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 13306:3306

volumes:
  servlet-mysql-store:
